# Generated by Django 3.2.7 on 2021-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_urlshortener_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='redirect_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
